### PR TITLE
Update to handle large raids

### PR DESCRIPTION
**Pull request by Omnituens**
Fixes server lagging out by splitting explosive delivery into batches of 10 every 60 game ticks
Fixes issue with large deliveries landing in a doughnut shape far away from player

### CODE REVIEW

**Comment by muppet9010** [comment]
Hi,

I see what your trying to do here, but to add it to the mod it would all need to be optionally parameter driven.
I'm not developing the Factorio mods any more myself so the PR would need to be suitable for all users use case to be merged. I am guessing you are using a copy of this fix locally already.

**Comment by Omnituens** [comment]
Yes, I made the alterations for Cl0wnt0wn after he got hit with a big raid and his server died.
By "parameter driven" do you mean as in you would like those values (as in time between batches and batch size) passed into the function ExplosiveDelivery.ScheduleExplosiveDeliveryCommand via command? Such as passing in command.BatchSize and command.BatchDelay (for example)? Factorio mod dev is not something I am hugely into, lua isn't my primary language. I only put this work around in as a favour so Cl0wn didn't have to worry about a raid binning the server.

**Comment by muppet9010** [comment]
Yes "paramater driven" I meant adding it in to the command syntax like you said. So having the options documented, parsing valid values (as other options are) on command execution and then passing the values through the code to the explosive creation logic part of the code.
As I know another streamer has had 15-20 grenades over a largish area before and it worked fine. So I always try to avoid hard coding something for a streamer if it can be configurable for them as they always change their mind at short notice lol.

**Comment by Omnituens** [comment]
OK I think I updated the command in the way you recommended. I'm a bit of a git noob so I am unsure if I need to put in a new pull request or not.

The use case was streamer had raid size of 1500 and was using nukes. 1500 nukes in 1 tick crashed the server. The client wasn't doing well either.

**Comment by muppet9010** [comment]
Yea we can just keep on adding to the existing Pull Request as then it has the history in one place.
I've had a look over the changes and made some amendments that seemed right to me and I believe still maintains the changes you were looking for. Have a look over them and shout if I've lost an intentional part of your changes.

**Comment by Omnituens** [comment]
The creation position was causing odd behaviour with large values - it seems to be causing the nukes to land waaaay away from the target destination in a ring. Not sure if we have footage of that issue, but after experimentation I found it was caused by the spawn position code. I couldn't see anything wrong with the maths functions being used, so I had assumed it was being passed bad data. Maybe something was causing min to be larger than max and it game was just handling it in an odd way?

**Comment by muppet9010** [comment]
So I tested the below a few times each and they all seemed to distribute as I'd expect:
1. Just large radius: `/muppet_streamer_schedule_explosive_delivery {"delay":5, "explosiveCount":200, "explosiveType":"atomicRocket", "target":"muppet9010", "accuracyRadiusMax":500, "salvoSize":30, "salvoDelay":60}`
2. Large radius and middle min radius; `/muppet_streamer_schedule_explosive_delivery {"delay":5, "explosiveCount":200, "explosiveType":"atomicRocket", "target":"muppet9010", "accuracyRadiusMin": 200, "accuracyRadiusMax":600, "salvoSize":30, "salvoDelay":60}`

Setting a larger min than max radius did create a circle of nukes between 400 and 500 which I guess makes sense as the random distance calculation just blindly applies the numbers and so does between 400 and `400 - -100`.
`/muppet_streamer_schedule_explosive_delivery {"delay":5, "explosiveCount":200, "explosiveType":"atomicRocket", "target":"muppet9010", "accuracyRadiusMin": 500, "accuracyRadiusMax":400, "salvoSize":30, "salvoDelay":60}`

I'm gonna commit and release this and if we can find a future example where it does behave oddly then I'm sure we can quickly find the cause and fix from the reproduction steps :)

**Pull request merged**
